# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.0.4
_src_path: gh:mjun0812/python-copier-template
author_email: mjun@mjunya.com
author_name: Junya Morioka
description: Modern Python Project
package_name: my_package
project_name: Python-Project-Template
python_version: '3.12'
